spring:
  datasource:
    url : jdbc:postgresql://localhost/phase4
    username : postgres
    password : post457
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  mail:
    host: smtp.gmail.com
    port: 587
    username: alvandiyan77@gmail.com
    password: 
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
        auth: true



  security:
    user:
      name: admin
      password: admin


server:
  error:
    include-message: always
